Add ability to load and save TPP configs from TPP popup window
ros-industrial-consortium/scan_n_plan_workshop pull request #138
Opened 2024-09-04 19:08 UTC by marrts

Save and loading TPP configs is a thing in the main noether GUI app, but I didn't see any way to do it in the window that SNP brings up. This adds those two items from the toolbar to the window that pops up.

![image](https://github.com/user-attachments/assets/2ded2d05-5029-4a55-b1f2-1bebd6784220)

2024-09-05 23:01 UTC, marip8 requested changes

2024-09-05 23:15 UTC, marrts commented on snp_application/src/snp_widget.cpp
> +  snp_tpp::TPPWidget* tpp_widget_;
The underlay Qt object is going form a Widget to a MainWindow. I used a main window to get a toolbar, and that meant I had to bring it up in a different way. If there is a simpler way that would be great, but this is all I could get working after poking around for a while, Qt stuff isn't my strength.

2024-09-05 23:15 UTC, marrts commented on snp_application/src/snp_widget.cpp
> +    connect(ui_->tool_button_tpp, &QToolButton::clicked, tpp_dialog, &TPPDialog::showTPPWidget);
Yeah, depending on the above stuff, I agree

2024-09-05 23:16 UTC, marrts commented on snp_tpp/src/tpp_widget.cpp
> +#include "ui_tpp_widget.h"
I didn't think a widget could have a toolbar, but if it can then that would be the way to go

2024-09-05 23:30 UTC, marip8 commented on snp_tpp/src/tpp_widget.cpp
> +#include "ui_tpp_widget.h"
Yeah, it's a widget just like anything else. I found out how to do this on the CTA project and it works pretty well. You can also define `QAction`s in the UI editor for any widget as well which makes it easy too

2024-09-12 15:05 UTC, marrts commented
@marip8, I significantly simplified this per your recommendations

2024-09-19 17:15 UTC, marip8 approved these changes
Looks good. Thanks for revising

2024-09-19 17:15 UTC, merged