Converted Scanning Node from C++ to Python
ros-industrial-consortium/scan_n_plan_workshop pull request #58
Opened 2023-11-03 22:47 UTC by DavidSpielman

Implementation of open_3d_sim_node.cpp in python. Generates a visualization_msgs Marker message that can be used to test motion planning in simulation.

2023-11-06 16:04 UTC, marip8 commented
Please rebase onto master and drop the commits from #47

2023-11-06 16:52 UTC, marip8 requested changes

2023-11-06 16:52 UTC, marip8 commented on snp_scanning/snp_scanning/__init__.py
Is this file necessary, since we only have a Python script?

2023-11-06 16:52 UTC, marip8 commented on snp_scanning/src/open3d_sim_node.cpp
Remove this file completely

2023-11-06 16:52 UTC, marip8 commented on snp_scanning/package.xml
>    <depend>rclcpp</depend>
```suggestion
```

2023-11-06 16:52 UTC, marip8 commented on snp_scanning/package.xml
>    <buildtool_depend>ament_cmake</buildtool_depend>
```suggestion
```

2023-11-06 16:52 UTC, marip8 commented on snp_automate_2022/launch/start.launch.xml
> +      <remap from="mesh" to="open3d_mesh"/>
I think the topic has a different name than `open3d_mesh`

```suggestion
      <remap from="mesh" to="industrial_reconstruction_mesh"/>
```

2023-11-06 18:02 UTC, DavidSpielman commented on snp_scanning/snp_scanning/__init__.py
Yes, this is how ROS2 finds the package. See [here](https://docs.ros.org/en/foxy/Tutorials/Beginner-Client-Libraries/Creating-Your-First-ROS2-Package.html#:~:text=ROS%202%20Python%20and%20CMake%20packages%20each%20have%20their%20own%20minimum%20required%20contents%3A)

2023-12-07 18:52 UTC, marip8 commented on snp_scanning/snp_scanning/__init__.py
FWIW, you don't actually need this. This is only necessary for ROS2 to find Python modules associated with this package. Since we don't have any modules in this package (only an executable script), this is and the call to `ament_python_install_package` are not necessary

2023-12-07 20:08 UTC, closed without merging